name: safe_safai_shop
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

#----------------packages---------------#
dependencies:
  flutter:
    sdk: flutter

  #Utility packages
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  lottie: ^3.3.1
  url_launcher: ^6.3.1
  connectivity_plus: ^5.0.2
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1


  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  #state management
  get: ^4.6.6
  get_storage: ^2.1.1

  #Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1

  # firebase
  firebase_core: ^2.23.0
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.13.5


#-----------------./Package end---------------#
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  #------------Local Assets-------------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/user/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
    - assets/icons/payment_methods/
    - assets/icons/categories/

  #------------Local fonts--------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 300
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 500
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 600
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 400
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 500
#        - assets:
#          weight:
#        - assets:
#          weight:
#        - assets:
#          weight:
#        - assets:
#          weight: