// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbxPmFf_VilCFT8Fu83UlZHFFbhRb0H0Q',
    appId: '1:578876174093:web:2be20dd9de6f808c638a44',
    messagingSenderId: '578876174093',
    projectId: 'safe-safai-shop-app',
    authDomain: 'safe-safai-shop-app.firebaseapp.com',
    storageBucket: 'safe-safai-shop-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiqqww1dAf9uFsS4QK4_tFPYZ2KA0Z7kI',
    appId: '1:578876174093:android:17d181c59334ba12638a44',
    messagingSenderId: '578876174093',
    projectId: 'safe-safai-shop-app',
    storageBucket: 'safe-safai-shop-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJeufwJMwQ3y37Ah0t9tWgehPD2aq1TwU',
    appId: '1:578876174093:ios:1748c7d5137e069a638a44',
    messagingSenderId: '578876174093',
    projectId: 'safe-safai-shop-app',
    storageBucket: 'safe-safai-shop-app.firebasestorage.app',
    androidClientId: '578876174093-j2s2bt22gte8pi47oum9fhh88u5as165.apps.googleusercontent.com',
    iosClientId: '578876174093-l0qr4of3lhrmafpb3634kbsojftkdftv.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeSafaiShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJeufwJMwQ3y37Ah0t9tWgehPD2aq1TwU',
    appId: '1:578876174093:ios:1748c7d5137e069a638a44',
    messagingSenderId: '578876174093',
    projectId: 'safe-safai-shop-app',
    storageBucket: 'safe-safai-shop-app.firebasestorage.app',
    androidClientId: '578876174093-j2s2bt22gte8pi47oum9fhh88u5as165.apps.googleusercontent.com',
    iosClientId: '578876174093-l0qr4of3lhrmafpb3634kbsojftkdftv.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeSafaiShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbxPmFf_VilCFT8Fu83UlZHFFbhRb0H0Q',
    appId: '1:578876174093:web:7587cfe725196fa3638a44',
    messagingSenderId: '578876174093',
    projectId: 'safe-safai-shop-app',
    authDomain: 'safe-safai-shop-app.firebaseapp.com',
    storageBucket: 'safe-safai-shop-app.firebasestorage.app',
  );

}